package com.unnet.triangle.lvs.master.mapper;

import com.unnet.triangle.lvs.master.model.ConfigVrrpInstanceExt;
import com.unnet.triangle.lvs.master.model.ConfigVrrpInstanceExtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigVrrpInstanceExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    long countByExample(ConfigVrrpInstanceExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    int deleteByExample(ConfigVrrpInstanceExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    int insert(ConfigVrrpInstanceExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    int insertSelective(ConfigVrrpInstanceExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    List<ConfigVrrpInstanceExt> selectByExample(ConfigVrrpInstanceExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    ConfigVrrpInstanceExt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConfigVrrpInstanceExt record, @Param("example") ConfigVrrpInstanceExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConfigVrrpInstanceExt record, @Param("example") ConfigVrrpInstanceExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigVrrpInstanceExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfigVrrpInstanceExt record);
}