package com.unnet.triangle.lvs.master.mapper;

import com.unnet.triangle.lvs.master.model.ConfigVirtualServerRealserverExt;
import com.unnet.triangle.lvs.master.model.ConfigVirtualServerRealserverExtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigVirtualServerRealserverExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    long countByExample(ConfigVirtualServerRealserverExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    int deleteByExample(ConfigVirtualServerRealserverExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    int insert(ConfigVirtualServerRealserverExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    int insertSelective(ConfigVirtualServerRealserverExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    List<ConfigVirtualServerRealserverExt> selectByExample(ConfigVirtualServerRealserverExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    ConfigVirtualServerRealserverExt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConfigVirtualServerRealserverExt record, @Param("example") ConfigVirtualServerRealserverExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConfigVirtualServerRealserverExt record, @Param("example") ConfigVirtualServerRealserverExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigVirtualServerRealserverExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfigVirtualServerRealserverExt record);
}