package com.unnet.triangle.lvs.master.mapper;

import com.unnet.triangle.lvs.master.model.ConfigVrrpSyncGroupExt;
import com.unnet.triangle.lvs.master.model.ConfigVrrpSyncGroupExtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigVrrpSyncGroupExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    long countByExample(ConfigVrrpSyncGroupExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    int deleteByExample(ConfigVrrpSyncGroupExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    int insert(ConfigVrrpSyncGroupExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    int insertSelective(ConfigVrrpSyncGroupExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    List<ConfigVrrpSyncGroupExt> selectByExample(ConfigVrrpSyncGroupExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    ConfigVrrpSyncGroupExt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConfigVrrpSyncGroupExt record, @Param("example") ConfigVrrpSyncGroupExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConfigVrrpSyncGroupExt record, @Param("example") ConfigVrrpSyncGroupExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigVrrpSyncGroupExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_sync_group_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfigVrrpSyncGroupExt record);
}