package com.unnet.triangle.lvs.master.mapper;

import com.unnet.triangle.lvs.master.model.ConfigVirtualServerRealserver;
import com.unnet.triangle.lvs.master.model.ConfigVirtualServerRealserverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigVirtualServerRealserverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    long countByExample(ConfigVirtualServerRealserverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    int deleteByExample(ConfigVirtualServerRealserverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    int insert(ConfigVirtualServerRealserver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    int insertSelective(ConfigVirtualServerRealserver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    List<ConfigVirtualServerRealserver> selectByExample(ConfigVirtualServerRealserverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    ConfigVirtualServerRealserver selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConfigVirtualServerRealserver record, @Param("example") ConfigVirtualServerRealserverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConfigVirtualServerRealserver record, @Param("example") ConfigVirtualServerRealserverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigVirtualServerRealserver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfigVirtualServerRealserver record);
}