package com.unnet.triangle.lvs.master.mapper;

import com.unnet.triangle.lvs.master.model.ConfigVrrpInstanceVip;
import com.unnet.triangle.lvs.master.model.ConfigVrrpInstanceVipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigVrrpInstanceVipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    long countByExample(ConfigVrrpInstanceVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    int deleteByExample(ConfigVrrpInstanceVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    int insert(ConfigVrrpInstanceVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    int insertSelective(ConfigVrrpInstanceVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    List<ConfigVrrpInstanceVip> selectByExample(ConfigVrrpInstanceVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    ConfigVrrpInstanceVip selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConfigVrrpInstanceVip record, @Param("example") ConfigVrrpInstanceVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConfigVrrpInstanceVip record, @Param("example") ConfigVrrpInstanceVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigVrrpInstanceVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_vrrp_instance_vip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfigVrrpInstanceVip record);
}