package com.unnet.triangle.lvs.master.mapper;

import com.unnet.triangle.lvs.master.model.ConfigVirtualServer;
import com.unnet.triangle.lvs.master.model.ConfigVirtualServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigVirtualServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    long countByExample(ConfigVirtualServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    int deleteByExample(ConfigVirtualServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    int insert(ConfigVirtualServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    int insertSelective(ConfigVirtualServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    List<ConfigVirtualServer> selectByExample(ConfigVirtualServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    ConfigVirtualServer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConfigVirtualServer record, @Param("example") ConfigVirtualServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConfigVirtualServer record, @Param("example") ConfigVirtualServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigVirtualServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfigVirtualServer record);
}