package com.unnet.triangle.lvs.master.mapper;

import com.unnet.triangle.lvs.master.model.ConfigExt;
import com.unnet.triangle.lvs.master.model.ConfigExtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    long countByExample(ConfigExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    int deleteByExample(ConfigExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    int insert(ConfigExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    int insertSelective(ConfigExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    List<ConfigExt> selectByExample(ConfigExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    ConfigExt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConfigExt record, @Param("example") ConfigExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConfigExt record, @Param("example") ConfigExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfigExt record);
}