package com.unnet.triangle.lvs.master.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    public ConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConfig_idIsNull() {
            addCriterion("config_id is null");
            return (Criteria) this;
        }

        public Criteria andConfig_idIsNotNull() {
            addCriterion("config_id is not null");
            return (Criteria) this;
        }

        public Criteria andConfig_idEqualTo(Long value) {
            addCriterion("config_id =", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idNotEqualTo(Long value) {
            addCriterion("config_id <>", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idGreaterThan(Long value) {
            addCriterion("config_id >", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idGreaterThanOrEqualTo(Long value) {
            addCriterion("config_id >=", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idLessThan(Long value) {
            addCriterion("config_id <", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idLessThanOrEqualTo(Long value) {
            addCriterion("config_id <=", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idIn(List<Long> values) {
            addCriterion("config_id in", values, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idNotIn(List<Long> values) {
            addCriterion("config_id not in", values, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idBetween(Long value1, Long value2) {
            addCriterion("config_id between", value1, value2, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idNotBetween(Long value1, Long value2) {
            addCriterion("config_id not between", value1, value2, "config_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idIsNull() {
            addCriterion("router_id is null");
            return (Criteria) this;
        }

        public Criteria andRouter_idIsNotNull() {
            addCriterion("router_id is not null");
            return (Criteria) this;
        }

        public Criteria andRouter_idEqualTo(String value) {
            addCriterion("router_id =", value, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idNotEqualTo(String value) {
            addCriterion("router_id <>", value, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idGreaterThan(String value) {
            addCriterion("router_id >", value, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idGreaterThanOrEqualTo(String value) {
            addCriterion("router_id >=", value, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idLessThan(String value) {
            addCriterion("router_id <", value, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idLessThanOrEqualTo(String value) {
            addCriterion("router_id <=", value, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idLike(String value) {
            addCriterion("router_id like", value, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idNotLike(String value) {
            addCriterion("router_id not like", value, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idIn(List<String> values) {
            addCriterion("router_id in", values, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idNotIn(List<String> values) {
            addCriterion("router_id not in", values, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idBetween(String value1, String value2) {
            addCriterion("router_id between", value1, value2, "router_id");
            return (Criteria) this;
        }

        public Criteria andRouter_idNotBetween(String value1, String value2) {
            addCriterion("router_id not between", value1, value2, "router_id");
            return (Criteria) this;
        }

        public Criteria andNode_idIsNull() {
            addCriterion("node_id is null");
            return (Criteria) this;
        }

        public Criteria andNode_idIsNotNull() {
            addCriterion("node_id is not null");
            return (Criteria) this;
        }

        public Criteria andNode_idEqualTo(Long value) {
            addCriterion("node_id =", value, "node_id");
            return (Criteria) this;
        }

        public Criteria andNode_idNotEqualTo(Long value) {
            addCriterion("node_id <>", value, "node_id");
            return (Criteria) this;
        }

        public Criteria andNode_idGreaterThan(Long value) {
            addCriterion("node_id >", value, "node_id");
            return (Criteria) this;
        }

        public Criteria andNode_idGreaterThanOrEqualTo(Long value) {
            addCriterion("node_id >=", value, "node_id");
            return (Criteria) this;
        }

        public Criteria andNode_idLessThan(Long value) {
            addCriterion("node_id <", value, "node_id");
            return (Criteria) this;
        }

        public Criteria andNode_idLessThanOrEqualTo(Long value) {
            addCriterion("node_id <=", value, "node_id");
            return (Criteria) this;
        }

        public Criteria andNode_idIn(List<Long> values) {
            addCriterion("node_id in", values, "node_id");
            return (Criteria) this;
        }

        public Criteria andNode_idNotIn(List<Long> values) {
            addCriterion("node_id not in", values, "node_id");
            return (Criteria) this;
        }

        public Criteria andNode_idBetween(Long value1, Long value2) {
            addCriterion("node_id between", value1, value2, "node_id");
            return (Criteria) this;
        }

        public Criteria andNode_idNotBetween(Long value1, Long value2) {
            addCriterion("node_id not between", value1, value2, "node_id");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Date value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Date value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Date value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Date> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonIsNull() {
            addCriterion("lvs_sync_daemon is null");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonIsNotNull() {
            addCriterion("lvs_sync_daemon is not null");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonEqualTo(String value) {
            addCriterion("lvs_sync_daemon =", value, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonNotEqualTo(String value) {
            addCriterion("lvs_sync_daemon <>", value, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonGreaterThan(String value) {
            addCriterion("lvs_sync_daemon >", value, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonGreaterThanOrEqualTo(String value) {
            addCriterion("lvs_sync_daemon >=", value, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonLessThan(String value) {
            addCriterion("lvs_sync_daemon <", value, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonLessThanOrEqualTo(String value) {
            addCriterion("lvs_sync_daemon <=", value, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonLike(String value) {
            addCriterion("lvs_sync_daemon like", value, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonNotLike(String value) {
            addCriterion("lvs_sync_daemon not like", value, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonIn(List<String> values) {
            addCriterion("lvs_sync_daemon in", values, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonNotIn(List<String> values) {
            addCriterion("lvs_sync_daemon not in", values, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonBetween(String value1, String value2) {
            addCriterion("lvs_sync_daemon between", value1, value2, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_daemonNotBetween(String value1, String value2) {
            addCriterion("lvs_sync_daemon not between", value1, value2, "lvs_sync_daemon");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceIsNull() {
            addCriterion("lvs_sync_instance is null");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceIsNotNull() {
            addCriterion("lvs_sync_instance is not null");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceEqualTo(Integer value) {
            addCriterion("lvs_sync_instance =", value, "lvs_sync_instance");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceNotEqualTo(Integer value) {
            addCriterion("lvs_sync_instance <>", value, "lvs_sync_instance");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceGreaterThan(Integer value) {
            addCriterion("lvs_sync_instance >", value, "lvs_sync_instance");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceGreaterThanOrEqualTo(Integer value) {
            addCriterion("lvs_sync_instance >=", value, "lvs_sync_instance");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceLessThan(Integer value) {
            addCriterion("lvs_sync_instance <", value, "lvs_sync_instance");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceLessThanOrEqualTo(Integer value) {
            addCriterion("lvs_sync_instance <=", value, "lvs_sync_instance");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceIn(List<Integer> values) {
            addCriterion("lvs_sync_instance in", values, "lvs_sync_instance");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceNotIn(List<Integer> values) {
            addCriterion("lvs_sync_instance not in", values, "lvs_sync_instance");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceBetween(Integer value1, Integer value2) {
            addCriterion("lvs_sync_instance between", value1, value2, "lvs_sync_instance");
            return (Criteria) this;
        }

        public Criteria andLvs_sync_instanceNotBetween(Integer value1, Integer value2) {
            addCriterion("lvs_sync_instance not between", value1, value2, "lvs_sync_instance");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutIsNull() {
            addCriterion("lvs_timeout is null");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutIsNotNull() {
            addCriterion("lvs_timeout is not null");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutEqualTo(Integer value) {
            addCriterion("lvs_timeout =", value, "lvs_timeout");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutNotEqualTo(Integer value) {
            addCriterion("lvs_timeout <>", value, "lvs_timeout");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutGreaterThan(Integer value) {
            addCriterion("lvs_timeout >", value, "lvs_timeout");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("lvs_timeout >=", value, "lvs_timeout");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutLessThan(Integer value) {
            addCriterion("lvs_timeout <", value, "lvs_timeout");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutLessThanOrEqualTo(Integer value) {
            addCriterion("lvs_timeout <=", value, "lvs_timeout");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutIn(List<Integer> values) {
            addCriterion("lvs_timeout in", values, "lvs_timeout");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutNotIn(List<Integer> values) {
            addCriterion("lvs_timeout not in", values, "lvs_timeout");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutBetween(Integer value1, Integer value2) {
            addCriterion("lvs_timeout between", value1, value2, "lvs_timeout");
            return (Criteria) this;
        }

        public Criteria andLvs_timeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("lvs_timeout not between", value1, value2, "lvs_timeout");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}