package com.unnet.triangle.lvs.master.model;

public class ConfigVrrpSyncGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_sync_group.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_sync_group.config_id
     *
     * @mbg.generated
     */
    private Long config_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_sync_group.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_sync_group.instance_name
     *
     * @mbg.generated
     */
    private String instance_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_sync_group.id
     *
     * @return the value of config_vrrp_sync_group.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_sync_group.id
     *
     * @param id the value for config_vrrp_sync_group.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_sync_group.config_id
     *
     * @return the value of config_vrrp_sync_group.config_id
     *
     * @mbg.generated
     */
    public Long getConfig_id() {
        return config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_sync_group.config_id
     *
     * @param config_id the value for config_vrrp_sync_group.config_id
     *
     * @mbg.generated
     */
    public void setConfig_id(Long config_id) {
        this.config_id = config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_sync_group.name
     *
     * @return the value of config_vrrp_sync_group.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_sync_group.name
     *
     * @param name the value for config_vrrp_sync_group.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_sync_group.instance_name
     *
     * @return the value of config_vrrp_sync_group.instance_name
     *
     * @mbg.generated
     */
    public String getInstance_name() {
        return instance_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_sync_group.instance_name
     *
     * @param instance_name the value for config_vrrp_sync_group.instance_name
     *
     * @mbg.generated
     */
    public void setInstance_name(String instance_name) {
        this.instance_name = instance_name;
    }
}