package com.unnet.triangle.lvs.master.model;

import java.util.ArrayList;
import java.util.List;

public class ConfigVirtualServerRealserverExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public ConfigVirtualServerRealserverExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idIsNull() {
            addCriterion("virtualserver_id is null");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idIsNotNull() {
            addCriterion("virtualserver_id is not null");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idEqualTo(Long value) {
            addCriterion("virtualserver_id =", value, "virtualserver_id");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idNotEqualTo(Long value) {
            addCriterion("virtualserver_id <>", value, "virtualserver_id");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idGreaterThan(Long value) {
            addCriterion("virtualserver_id >", value, "virtualserver_id");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idGreaterThanOrEqualTo(Long value) {
            addCriterion("virtualserver_id >=", value, "virtualserver_id");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idLessThan(Long value) {
            addCriterion("virtualserver_id <", value, "virtualserver_id");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idLessThanOrEqualTo(Long value) {
            addCriterion("virtualserver_id <=", value, "virtualserver_id");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idIn(List<Long> values) {
            addCriterion("virtualserver_id in", values, "virtualserver_id");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idNotIn(List<Long> values) {
            addCriterion("virtualserver_id not in", values, "virtualserver_id");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idBetween(Long value1, Long value2) {
            addCriterion("virtualserver_id between", value1, value2, "virtualserver_id");
            return (Criteria) this;
        }

        public Criteria andVirtualserver_idNotBetween(Long value1, Long value2) {
            addCriterion("virtualserver_id not between", value1, value2, "virtualserver_id");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andPortIsNull() {
            addCriterion("port is null");
            return (Criteria) this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("port is not null");
            return (Criteria) this;
        }

        public Criteria andPortEqualTo(Integer value) {
            addCriterion("port =", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotEqualTo(Integer value) {
            addCriterion("port <>", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThan(Integer value) {
            addCriterion("port >", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("port >=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThan(Integer value) {
            addCriterion("port <", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThanOrEqualTo(Integer value) {
            addCriterion("port <=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortIn(List<Integer> values) {
            addCriterion("port in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotIn(List<Integer> values) {
            addCriterion("port not in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortBetween(Integer value1, Integer value2) {
            addCriterion("port between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotBetween(Integer value1, Integer value2) {
            addCriterion("port not between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureIsNull() {
            addCriterion("inhibit_on_failure is null");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureIsNotNull() {
            addCriterion("inhibit_on_failure is not null");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureEqualTo(String value) {
            addCriterion("inhibit_on_failure =", value, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureNotEqualTo(String value) {
            addCriterion("inhibit_on_failure <>", value, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureGreaterThan(String value) {
            addCriterion("inhibit_on_failure >", value, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureGreaterThanOrEqualTo(String value) {
            addCriterion("inhibit_on_failure >=", value, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureLessThan(String value) {
            addCriterion("inhibit_on_failure <", value, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureLessThanOrEqualTo(String value) {
            addCriterion("inhibit_on_failure <=", value, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureLike(String value) {
            addCriterion("inhibit_on_failure like", value, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureNotLike(String value) {
            addCriterion("inhibit_on_failure not like", value, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureIn(List<String> values) {
            addCriterion("inhibit_on_failure in", values, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureNotIn(List<String> values) {
            addCriterion("inhibit_on_failure not in", values, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureBetween(String value1, String value2) {
            addCriterion("inhibit_on_failure between", value1, value2, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andInhibit_on_failureNotBetween(String value1, String value2) {
            addCriterion("inhibit_on_failure not between", value1, value2, "inhibit_on_failure");
            return (Criteria) this;
        }

        public Criteria andCheak_typeIsNull() {
            addCriterion("cheak_type is null");
            return (Criteria) this;
        }

        public Criteria andCheak_typeIsNotNull() {
            addCriterion("cheak_type is not null");
            return (Criteria) this;
        }

        public Criteria andCheak_typeEqualTo(String value) {
            addCriterion("cheak_type =", value, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeNotEqualTo(String value) {
            addCriterion("cheak_type <>", value, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeGreaterThan(String value) {
            addCriterion("cheak_type >", value, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeGreaterThanOrEqualTo(String value) {
            addCriterion("cheak_type >=", value, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeLessThan(String value) {
            addCriterion("cheak_type <", value, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeLessThanOrEqualTo(String value) {
            addCriterion("cheak_type <=", value, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeLike(String value) {
            addCriterion("cheak_type like", value, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeNotLike(String value) {
            addCriterion("cheak_type not like", value, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeIn(List<String> values) {
            addCriterion("cheak_type in", values, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeNotIn(List<String> values) {
            addCriterion("cheak_type not in", values, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeBetween(String value1, String value2) {
            addCriterion("cheak_type between", value1, value2, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andCheak_typeNotBetween(String value1, String value2) {
            addCriterion("cheak_type not between", value1, value2, "cheak_type");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutIsNull() {
            addCriterion("connect_timeout is null");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutIsNotNull() {
            addCriterion("connect_timeout is not null");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutEqualTo(Integer value) {
            addCriterion("connect_timeout =", value, "connect_timeout");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutNotEqualTo(Integer value) {
            addCriterion("connect_timeout <>", value, "connect_timeout");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutGreaterThan(Integer value) {
            addCriterion("connect_timeout >", value, "connect_timeout");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("connect_timeout >=", value, "connect_timeout");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutLessThan(Integer value) {
            addCriterion("connect_timeout <", value, "connect_timeout");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutLessThanOrEqualTo(Integer value) {
            addCriterion("connect_timeout <=", value, "connect_timeout");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutIn(List<Integer> values) {
            addCriterion("connect_timeout in", values, "connect_timeout");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutNotIn(List<Integer> values) {
            addCriterion("connect_timeout not in", values, "connect_timeout");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutBetween(Integer value1, Integer value2) {
            addCriterion("connect_timeout between", value1, value2, "connect_timeout");
            return (Criteria) this;
        }

        public Criteria andConnect_timeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("connect_timeout not between", value1, value2, "connect_timeout");
            return (Criteria) this;
        }

        public Criteria andWhereIsNull() {
            addCriterion("`where` is null");
            return (Criteria) this;
        }

        public Criteria andWhereIsNotNull() {
            addCriterion("`where` is not null");
            return (Criteria) this;
        }

        public Criteria andWhereEqualTo(String value) {
            addCriterion("`where` =", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereNotEqualTo(String value) {
            addCriterion("`where` <>", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereGreaterThan(String value) {
            addCriterion("`where` >", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereGreaterThanOrEqualTo(String value) {
            addCriterion("`where` >=", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereLessThan(String value) {
            addCriterion("`where` <", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereLessThanOrEqualTo(String value) {
            addCriterion("`where` <=", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereLike(String value) {
            addCriterion("`where` like", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereNotLike(String value) {
            addCriterion("`where` not like", value, "where");
            return (Criteria) this;
        }

        public Criteria andWhereIn(List<String> values) {
            addCriterion("`where` in", values, "where");
            return (Criteria) this;
        }

        public Criteria andWhereNotIn(List<String> values) {
            addCriterion("`where` not in", values, "where");
            return (Criteria) this;
        }

        public Criteria andWhereBetween(String value1, String value2) {
            addCriterion("`where` between", value1, value2, "where");
            return (Criteria) this;
        }

        public Criteria andWhereNotBetween(String value1, String value2) {
            addCriterion("`where` not between", value1, value2, "where");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config_virtual_server_realserver
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}