package com.unnet.triangle.lvs.master.model;

public class ConfigVrrpInstance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance.config_id
     *
     * @mbg.generated
     */
    private Long config_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance.network_interface
     *
     * @mbg.generated
     */
    private String network_interface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance.virtual_router_id
     *
     * @mbg.generated
     */
    private Integer virtual_router_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance.advert
     *
     * @mbg.generated
     */
    private Integer advert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance.no_preempt
     *
     * @mbg.generated
     */
    private String no_preempt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance.id
     *
     * @return the value of config_vrrp_instance.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance.id
     *
     * @param id the value for config_vrrp_instance.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance.config_id
     *
     * @return the value of config_vrrp_instance.config_id
     *
     * @mbg.generated
     */
    public Long getConfig_id() {
        return config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance.config_id
     *
     * @param config_id the value for config_vrrp_instance.config_id
     *
     * @mbg.generated
     */
    public void setConfig_id(Long config_id) {
        this.config_id = config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance.name
     *
     * @return the value of config_vrrp_instance.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance.name
     *
     * @param name the value for config_vrrp_instance.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance.state
     *
     * @return the value of config_vrrp_instance.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance.state
     *
     * @param state the value for config_vrrp_instance.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance.network_interface
     *
     * @return the value of config_vrrp_instance.network_interface
     *
     * @mbg.generated
     */
    public String getNetwork_interface() {
        return network_interface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance.network_interface
     *
     * @param network_interface the value for config_vrrp_instance.network_interface
     *
     * @mbg.generated
     */
    public void setNetwork_interface(String network_interface) {
        this.network_interface = network_interface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance.virtual_router_id
     *
     * @return the value of config_vrrp_instance.virtual_router_id
     *
     * @mbg.generated
     */
    public Integer getVirtual_router_id() {
        return virtual_router_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance.virtual_router_id
     *
     * @param virtual_router_id the value for config_vrrp_instance.virtual_router_id
     *
     * @mbg.generated
     */
    public void setVirtual_router_id(Integer virtual_router_id) {
        this.virtual_router_id = virtual_router_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance.priority
     *
     * @return the value of config_vrrp_instance.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance.priority
     *
     * @param priority the value for config_vrrp_instance.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance.advert
     *
     * @return the value of config_vrrp_instance.advert
     *
     * @mbg.generated
     */
    public Integer getAdvert() {
        return advert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance.advert
     *
     * @param advert the value for config_vrrp_instance.advert
     *
     * @mbg.generated
     */
    public void setAdvert(Integer advert) {
        this.advert = advert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance.no_preempt
     *
     * @return the value of config_vrrp_instance.no_preempt
     *
     * @mbg.generated
     */
    public String getNo_preempt() {
        return no_preempt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance.no_preempt
     *
     * @param no_preempt the value for config_vrrp_instance.no_preempt
     *
     * @mbg.generated
     */
    public void setNo_preempt(String no_preempt) {
        this.no_preempt = no_preempt;
    }
}