package com.unnet.triangle.lvs.master.model;

public class ConfigVirtualServerExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_ext.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_ext.vs_id
     *
     * @mbg.generated
     */
    private Long vs_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_ext.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_ext.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_ext.id
     *
     * @return the value of config_virtual_server_ext.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_ext.id
     *
     * @param id the value for config_virtual_server_ext.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_ext.vs_id
     *
     * @return the value of config_virtual_server_ext.vs_id
     *
     * @mbg.generated
     */
    public Long getVs_id() {
        return vs_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_ext.vs_id
     *
     * @param vs_id the value for config_virtual_server_ext.vs_id
     *
     * @mbg.generated
     */
    public void setVs_id(Long vs_id) {
        this.vs_id = vs_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_ext.name
     *
     * @return the value of config_virtual_server_ext.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_ext.name
     *
     * @param name the value for config_virtual_server_ext.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_ext.value
     *
     * @return the value of config_virtual_server_ext.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_ext.value
     *
     * @param value the value for config_virtual_server_ext.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value;
    }
}