package com.unnet.triangle.lvs.master.model;

import java.util.ArrayList;
import java.util.List;

public class ConfigVirtualServerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public ConfigVirtualServerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andConfig_idIsNull() {
            addCriterion("config_id is null");
            return (Criteria) this;
        }

        public Criteria andConfig_idIsNotNull() {
            addCriterion("config_id is not null");
            return (Criteria) this;
        }

        public Criteria andConfig_idEqualTo(Long value) {
            addCriterion("config_id =", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idNotEqualTo(Long value) {
            addCriterion("config_id <>", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idGreaterThan(Long value) {
            addCriterion("config_id >", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idGreaterThanOrEqualTo(Long value) {
            addCriterion("config_id >=", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idLessThan(Long value) {
            addCriterion("config_id <", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idLessThanOrEqualTo(Long value) {
            addCriterion("config_id <=", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idIn(List<Long> values) {
            addCriterion("config_id in", values, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idNotIn(List<Long> values) {
            addCriterion("config_id not in", values, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idBetween(Long value1, Long value2) {
            addCriterion("config_id between", value1, value2, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idNotBetween(Long value1, Long value2) {
            addCriterion("config_id not between", value1, value2, "config_id");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andPortIsNull() {
            addCriterion("port is null");
            return (Criteria) this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("port is not null");
            return (Criteria) this;
        }

        public Criteria andPortEqualTo(Integer value) {
            addCriterion("port =", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotEqualTo(Integer value) {
            addCriterion("port <>", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThan(Integer value) {
            addCriterion("port >", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("port >=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThan(Integer value) {
            addCriterion("port <", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThanOrEqualTo(Integer value) {
            addCriterion("port <=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortIn(List<Integer> values) {
            addCriterion("port in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotIn(List<Integer> values) {
            addCriterion("port not in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortBetween(Integer value1, Integer value2) {
            addCriterion("port between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotBetween(Integer value1, Integer value2) {
            addCriterion("port not between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andDelayIsNull() {
            addCriterion("delay is null");
            return (Criteria) this;
        }

        public Criteria andDelayIsNotNull() {
            addCriterion("delay is not null");
            return (Criteria) this;
        }

        public Criteria andDelayEqualTo(Integer value) {
            addCriterion("delay =", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotEqualTo(Integer value) {
            addCriterion("delay <>", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayGreaterThan(Integer value) {
            addCriterion("delay >", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayGreaterThanOrEqualTo(Integer value) {
            addCriterion("delay >=", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayLessThan(Integer value) {
            addCriterion("delay <", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayLessThanOrEqualTo(Integer value) {
            addCriterion("delay <=", value, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayIn(List<Integer> values) {
            addCriterion("delay in", values, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotIn(List<Integer> values) {
            addCriterion("delay not in", values, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayBetween(Integer value1, Integer value2) {
            addCriterion("delay between", value1, value2, "delay");
            return (Criteria) this;
        }

        public Criteria andDelayNotBetween(Integer value1, Integer value2) {
            addCriterion("delay not between", value1, value2, "delay");
            return (Criteria) this;
        }

        public Criteria andLb_algoIsNull() {
            addCriterion("lb_algo is null");
            return (Criteria) this;
        }

        public Criteria andLb_algoIsNotNull() {
            addCriterion("lb_algo is not null");
            return (Criteria) this;
        }

        public Criteria andLb_algoEqualTo(String value) {
            addCriterion("lb_algo =", value, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoNotEqualTo(String value) {
            addCriterion("lb_algo <>", value, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoGreaterThan(String value) {
            addCriterion("lb_algo >", value, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoGreaterThanOrEqualTo(String value) {
            addCriterion("lb_algo >=", value, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoLessThan(String value) {
            addCriterion("lb_algo <", value, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoLessThanOrEqualTo(String value) {
            addCriterion("lb_algo <=", value, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoLike(String value) {
            addCriterion("lb_algo like", value, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoNotLike(String value) {
            addCriterion("lb_algo not like", value, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoIn(List<String> values) {
            addCriterion("lb_algo in", values, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoNotIn(List<String> values) {
            addCriterion("lb_algo not in", values, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoBetween(String value1, String value2) {
            addCriterion("lb_algo between", value1, value2, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andLb_algoNotBetween(String value1, String value2) {
            addCriterion("lb_algo not between", value1, value2, "lb_algo");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutIsNull() {
            addCriterion("persistence_timeout is null");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutIsNotNull() {
            addCriterion("persistence_timeout is not null");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutEqualTo(Integer value) {
            addCriterion("persistence_timeout =", value, "persistence_timeout");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutNotEqualTo(Integer value) {
            addCriterion("persistence_timeout <>", value, "persistence_timeout");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutGreaterThan(Integer value) {
            addCriterion("persistence_timeout >", value, "persistence_timeout");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("persistence_timeout >=", value, "persistence_timeout");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutLessThan(Integer value) {
            addCriterion("persistence_timeout <", value, "persistence_timeout");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutLessThanOrEqualTo(Integer value) {
            addCriterion("persistence_timeout <=", value, "persistence_timeout");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutIn(List<Integer> values) {
            addCriterion("persistence_timeout in", values, "persistence_timeout");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutNotIn(List<Integer> values) {
            addCriterion("persistence_timeout not in", values, "persistence_timeout");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutBetween(Integer value1, Integer value2) {
            addCriterion("persistence_timeout between", value1, value2, "persistence_timeout");
            return (Criteria) this;
        }

        public Criteria andPersistence_timeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("persistence_timeout not between", value1, value2, "persistence_timeout");
            return (Criteria) this;
        }

        public Criteria andProtocolIsNull() {
            addCriterion("protocol is null");
            return (Criteria) this;
        }

        public Criteria andProtocolIsNotNull() {
            addCriterion("protocol is not null");
            return (Criteria) this;
        }

        public Criteria andProtocolEqualTo(String value) {
            addCriterion("protocol =", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotEqualTo(String value) {
            addCriterion("protocol <>", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolGreaterThan(String value) {
            addCriterion("protocol >", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolGreaterThanOrEqualTo(String value) {
            addCriterion("protocol >=", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLessThan(String value) {
            addCriterion("protocol <", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLessThanOrEqualTo(String value) {
            addCriterion("protocol <=", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLike(String value) {
            addCriterion("protocol like", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotLike(String value) {
            addCriterion("protocol not like", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolIn(List<String> values) {
            addCriterion("protocol in", values, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotIn(List<String> values) {
            addCriterion("protocol not in", values, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolBetween(String value1, String value2) {
            addCriterion("protocol between", value1, value2, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotBetween(String value1, String value2) {
            addCriterion("protocol not between", value1, value2, "protocol");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityIsNull() {
            addCriterion("persistence_granularity is null");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityIsNotNull() {
            addCriterion("persistence_granularity is not null");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityEqualTo(String value) {
            addCriterion("persistence_granularity =", value, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityNotEqualTo(String value) {
            addCriterion("persistence_granularity <>", value, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityGreaterThan(String value) {
            addCriterion("persistence_granularity >", value, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityGreaterThanOrEqualTo(String value) {
            addCriterion("persistence_granularity >=", value, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityLessThan(String value) {
            addCriterion("persistence_granularity <", value, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityLessThanOrEqualTo(String value) {
            addCriterion("persistence_granularity <=", value, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityLike(String value) {
            addCriterion("persistence_granularity like", value, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityNotLike(String value) {
            addCriterion("persistence_granularity not like", value, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityIn(List<String> values) {
            addCriterion("persistence_granularity in", values, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityNotIn(List<String> values) {
            addCriterion("persistence_granularity not in", values, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityBetween(String value1, String value2) {
            addCriterion("persistence_granularity between", value1, value2, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andPersistence_granularityNotBetween(String value1, String value2) {
            addCriterion("persistence_granularity not between", value1, value2, "persistence_granularity");
            return (Criteria) this;
        }

        public Criteria andSorry_serverIsNull() {
            addCriterion("sorry_server is null");
            return (Criteria) this;
        }

        public Criteria andSorry_serverIsNotNull() {
            addCriterion("sorry_server is not null");
            return (Criteria) this;
        }

        public Criteria andSorry_serverEqualTo(String value) {
            addCriterion("sorry_server =", value, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverNotEqualTo(String value) {
            addCriterion("sorry_server <>", value, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverGreaterThan(String value) {
            addCriterion("sorry_server >", value, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverGreaterThanOrEqualTo(String value) {
            addCriterion("sorry_server >=", value, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverLessThan(String value) {
            addCriterion("sorry_server <", value, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverLessThanOrEqualTo(String value) {
            addCriterion("sorry_server <=", value, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverLike(String value) {
            addCriterion("sorry_server like", value, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverNotLike(String value) {
            addCriterion("sorry_server not like", value, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverIn(List<String> values) {
            addCriterion("sorry_server in", values, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverNotIn(List<String> values) {
            addCriterion("sorry_server not in", values, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverBetween(String value1, String value2) {
            addCriterion("sorry_server between", value1, value2, "sorry_server");
            return (Criteria) this;
        }

        public Criteria andSorry_serverNotBetween(String value1, String value2) {
            addCriterion("sorry_server not between", value1, value2, "sorry_server");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config_virtual_server
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config_virtual_server
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}