package com.unnet.triangle.lvs.master.model;

public class ConfigExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_ext.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_ext.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_ext.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_ext.config_id
     *
     * @mbg.generated
     */
    private Long config_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_ext.id
     *
     * @return the value of config_ext.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_ext.id
     *
     * @param id the value for config_ext.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_ext.name
     *
     * @return the value of config_ext.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_ext.name
     *
     * @param name the value for config_ext.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_ext.value
     *
     * @return the value of config_ext.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_ext.value
     *
     * @param value the value for config_ext.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_ext.config_id
     *
     * @return the value of config_ext.config_id
     *
     * @mbg.generated
     */
    public Long getConfig_id() {
        return config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_ext.config_id
     *
     * @param config_id the value for config_ext.config_id
     *
     * @mbg.generated
     */
    public void setConfig_id(Long config_id) {
        this.config_id = config_id;
    }
}