package com.unnet.triangle.lvs.master.model;

public class ConfigVrrpInstanceVip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance_vip.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance_vip.instance_id
     *
     * @mbg.generated
     */
    private Long instance_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance_vip.vip
     *
     * @mbg.generated
     */
    private String vip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance_vip.id
     *
     * @return the value of config_vrrp_instance_vip.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance_vip.id
     *
     * @param id the value for config_vrrp_instance_vip.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance_vip.instance_id
     *
     * @return the value of config_vrrp_instance_vip.instance_id
     *
     * @mbg.generated
     */
    public Long getInstance_id() {
        return instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance_vip.instance_id
     *
     * @param instance_id the value for config_vrrp_instance_vip.instance_id
     *
     * @mbg.generated
     */
    public void setInstance_id(Long instance_id) {
        this.instance_id = instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance_vip.vip
     *
     * @return the value of config_vrrp_instance_vip.vip
     *
     * @mbg.generated
     */
    public String getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance_vip.vip
     *
     * @param vip the value for config_vrrp_instance_vip.vip
     *
     * @mbg.generated
     */
    public void setVip(String vip) {
        this.vip = vip;
    }
}