package com.unnet.triangle.lvs.master.model;

import java.util.Date;

public class Config {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.config_id
     *
     * @mbg.generated
     */
    private Long config_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.router_id
     *
     * @mbg.generated
     */
    private String router_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.node_id
     *
     * @mbg.generated
     */
    private Long node_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.update_time
     *
     * @mbg.generated
     */
    private Date update_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.lvs_sync_daemon
     *
     * @mbg.generated
     */
    private String lvs_sync_daemon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.lvs_sync_instance
     *
     * @mbg.generated
     */
    private Integer lvs_sync_instance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.lvs_timeout
     *
     * @mbg.generated
     */
    private Integer lvs_timeout;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.config_id
     *
     * @return the value of config.config_id
     *
     * @mbg.generated
     */
    public Long getConfig_id() {
        return config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.config_id
     *
     * @param config_id the value for config.config_id
     *
     * @mbg.generated
     */
    public void setConfig_id(Long config_id) {
        this.config_id = config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.router_id
     *
     * @return the value of config.router_id
     *
     * @mbg.generated
     */
    public String getRouter_id() {
        return router_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.router_id
     *
     * @param router_id the value for config.router_id
     *
     * @mbg.generated
     */
    public void setRouter_id(String router_id) {
        this.router_id = router_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.node_id
     *
     * @return the value of config.node_id
     *
     * @mbg.generated
     */
    public Long getNode_id() {
        return node_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.node_id
     *
     * @param node_id the value for config.node_id
     *
     * @mbg.generated
     */
    public void setNode_id(Long node_id) {
        this.node_id = node_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.create_time
     *
     * @return the value of config.create_time
     *
     * @mbg.generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.create_time
     *
     * @param create_time the value for config.create_time
     *
     * @mbg.generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.update_time
     *
     * @return the value of config.update_time
     *
     * @mbg.generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.update_time
     *
     * @param update_time the value for config.update_time
     *
     * @mbg.generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.lvs_sync_daemon
     *
     * @return the value of config.lvs_sync_daemon
     *
     * @mbg.generated
     */
    public String getLvs_sync_daemon() {
        return lvs_sync_daemon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.lvs_sync_daemon
     *
     * @param lvs_sync_daemon the value for config.lvs_sync_daemon
     *
     * @mbg.generated
     */
    public void setLvs_sync_daemon(String lvs_sync_daemon) {
        this.lvs_sync_daemon = lvs_sync_daemon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.lvs_sync_instance
     *
     * @return the value of config.lvs_sync_instance
     *
     * @mbg.generated
     */
    public Integer getLvs_sync_instance() {
        return lvs_sync_instance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.lvs_sync_instance
     *
     * @param lvs_sync_instance the value for config.lvs_sync_instance
     *
     * @mbg.generated
     */
    public void setLvs_sync_instance(Integer lvs_sync_instance) {
        this.lvs_sync_instance = lvs_sync_instance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.lvs_timeout
     *
     * @return the value of config.lvs_timeout
     *
     * @mbg.generated
     */
    public Integer getLvs_timeout() {
        return lvs_timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.lvs_timeout
     *
     * @param lvs_timeout the value for config.lvs_timeout
     *
     * @mbg.generated
     */
    public void setLvs_timeout(Integer lvs_timeout) {
        this.lvs_timeout = lvs_timeout;
    }
}