package com.unnet.triangle.lvs.master.model;

public class ConfigVirtualServer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server.config_id
     *
     * @mbg.generated
     */
    private Long config_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server.delay
     *
     * @mbg.generated
     */
    private Integer delay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server.lb_algo
     *
     * @mbg.generated
     */
    private String lb_algo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server.persistence_timeout
     *
     * @mbg.generated
     */
    private Integer persistence_timeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server.protocol
     *
     * @mbg.generated
     */
    private String protocol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server.persistence_granularity
     *
     * @mbg.generated
     */
    private String persistence_granularity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server.sorry_server
     *
     * @mbg.generated
     */
    private String sorry_server;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server.id
     *
     * @return the value of config_virtual_server.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server.id
     *
     * @param id the value for config_virtual_server.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server.config_id
     *
     * @return the value of config_virtual_server.config_id
     *
     * @mbg.generated
     */
    public Long getConfig_id() {
        return config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server.config_id
     *
     * @param config_id the value for config_virtual_server.config_id
     *
     * @mbg.generated
     */
    public void setConfig_id(Long config_id) {
        this.config_id = config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server.ip
     *
     * @return the value of config_virtual_server.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server.ip
     *
     * @param ip the value for config_virtual_server.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server.port
     *
     * @return the value of config_virtual_server.port
     *
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server.port
     *
     * @param port the value for config_virtual_server.port
     *
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server.delay
     *
     * @return the value of config_virtual_server.delay
     *
     * @mbg.generated
     */
    public Integer getDelay() {
        return delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server.delay
     *
     * @param delay the value for config_virtual_server.delay
     *
     * @mbg.generated
     */
    public void setDelay(Integer delay) {
        this.delay = delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server.lb_algo
     *
     * @return the value of config_virtual_server.lb_algo
     *
     * @mbg.generated
     */
    public String getLb_algo() {
        return lb_algo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server.lb_algo
     *
     * @param lb_algo the value for config_virtual_server.lb_algo
     *
     * @mbg.generated
     */
    public void setLb_algo(String lb_algo) {
        this.lb_algo = lb_algo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server.persistence_timeout
     *
     * @return the value of config_virtual_server.persistence_timeout
     *
     * @mbg.generated
     */
    public Integer getPersistence_timeout() {
        return persistence_timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server.persistence_timeout
     *
     * @param persistence_timeout the value for config_virtual_server.persistence_timeout
     *
     * @mbg.generated
     */
    public void setPersistence_timeout(Integer persistence_timeout) {
        this.persistence_timeout = persistence_timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server.protocol
     *
     * @return the value of config_virtual_server.protocol
     *
     * @mbg.generated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server.protocol
     *
     * @param protocol the value for config_virtual_server.protocol
     *
     * @mbg.generated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server.persistence_granularity
     *
     * @return the value of config_virtual_server.persistence_granularity
     *
     * @mbg.generated
     */
    public String getPersistence_granularity() {
        return persistence_granularity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server.persistence_granularity
     *
     * @param persistence_granularity the value for config_virtual_server.persistence_granularity
     *
     * @mbg.generated
     */
    public void setPersistence_granularity(String persistence_granularity) {
        this.persistence_granularity = persistence_granularity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server.sorry_server
     *
     * @return the value of config_virtual_server.sorry_server
     *
     * @mbg.generated
     */
    public String getSorry_server() {
        return sorry_server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server.sorry_server
     *
     * @param sorry_server the value for config_virtual_server.sorry_server
     *
     * @mbg.generated
     */
    public void setSorry_server(String sorry_server) {
        this.sorry_server = sorry_server;
    }
}