package com.unnet.triangle.lvs.master.model;

public class ConfigVrrpInstanceExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance_ext.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance_ext.instance_id
     *
     * @mbg.generated
     */
    private Long instance_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance_ext.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_vrrp_instance_ext.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance_ext.id
     *
     * @return the value of config_vrrp_instance_ext.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance_ext.id
     *
     * @param id the value for config_vrrp_instance_ext.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance_ext.instance_id
     *
     * @return the value of config_vrrp_instance_ext.instance_id
     *
     * @mbg.generated
     */
    public Long getInstance_id() {
        return instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance_ext.instance_id
     *
     * @param instance_id the value for config_vrrp_instance_ext.instance_id
     *
     * @mbg.generated
     */
    public void setInstance_id(Long instance_id) {
        this.instance_id = instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance_ext.name
     *
     * @return the value of config_vrrp_instance_ext.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance_ext.name
     *
     * @param name the value for config_vrrp_instance_ext.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_vrrp_instance_ext.value
     *
     * @return the value of config_vrrp_instance_ext.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_vrrp_instance_ext.value
     *
     * @param value the value for config_vrrp_instance_ext.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value;
    }
}