package com.unnet.triangle.lvs.master.model;

public class ConfigVirtualServerRealserver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_realserver.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_realserver.virtualserver_id
     *
     * @mbg.generated
     */
    private Long virtualserver_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_realserver.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_realserver.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_realserver.weight
     *
     * @mbg.generated
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_realserver.inhibit_on_failure
     *
     * @mbg.generated
     */
    private String inhibit_on_failure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_realserver.cheak_type
     *
     * @mbg.generated
     */
    private String cheak_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_realserver.connect_timeout
     *
     * @mbg.generated
     */
    private Integer connect_timeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_realserver.where
     *
     * @mbg.generated
     */
    private String where;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_virtual_server_realserver.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_realserver.id
     *
     * @return the value of config_virtual_server_realserver.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_realserver.id
     *
     * @param id the value for config_virtual_server_realserver.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_realserver.virtualserver_id
     *
     * @return the value of config_virtual_server_realserver.virtualserver_id
     *
     * @mbg.generated
     */
    public Long getVirtualserver_id() {
        return virtualserver_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_realserver.virtualserver_id
     *
     * @param virtualserver_id the value for config_virtual_server_realserver.virtualserver_id
     *
     * @mbg.generated
     */
    public void setVirtualserver_id(Long virtualserver_id) {
        this.virtualserver_id = virtualserver_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_realserver.ip
     *
     * @return the value of config_virtual_server_realserver.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_realserver.ip
     *
     * @param ip the value for config_virtual_server_realserver.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_realserver.port
     *
     * @return the value of config_virtual_server_realserver.port
     *
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_realserver.port
     *
     * @param port the value for config_virtual_server_realserver.port
     *
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_realserver.weight
     *
     * @return the value of config_virtual_server_realserver.weight
     *
     * @mbg.generated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_realserver.weight
     *
     * @param weight the value for config_virtual_server_realserver.weight
     *
     * @mbg.generated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_realserver.inhibit_on_failure
     *
     * @return the value of config_virtual_server_realserver.inhibit_on_failure
     *
     * @mbg.generated
     */
    public String getInhibit_on_failure() {
        return inhibit_on_failure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_realserver.inhibit_on_failure
     *
     * @param inhibit_on_failure the value for config_virtual_server_realserver.inhibit_on_failure
     *
     * @mbg.generated
     */
    public void setInhibit_on_failure(String inhibit_on_failure) {
        this.inhibit_on_failure = inhibit_on_failure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_realserver.cheak_type
     *
     * @return the value of config_virtual_server_realserver.cheak_type
     *
     * @mbg.generated
     */
    public String getCheak_type() {
        return cheak_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_realserver.cheak_type
     *
     * @param cheak_type the value for config_virtual_server_realserver.cheak_type
     *
     * @mbg.generated
     */
    public void setCheak_type(String cheak_type) {
        this.cheak_type = cheak_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_realserver.connect_timeout
     *
     * @return the value of config_virtual_server_realserver.connect_timeout
     *
     * @mbg.generated
     */
    public Integer getConnect_timeout() {
        return connect_timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_realserver.connect_timeout
     *
     * @param connect_timeout the value for config_virtual_server_realserver.connect_timeout
     *
     * @mbg.generated
     */
    public void setConnect_timeout(Integer connect_timeout) {
        this.connect_timeout = connect_timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_realserver.where
     *
     * @return the value of config_virtual_server_realserver.where
     *
     * @mbg.generated
     */
    public String getWhere() {
        return where;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_realserver.where
     *
     * @param where the value for config_virtual_server_realserver.where
     *
     * @mbg.generated
     */
    public void setWhere(String where) {
        this.where = where;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_virtual_server_realserver.status
     *
     * @return the value of config_virtual_server_realserver.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_virtual_server_realserver.status
     *
     * @param status the value for config_virtual_server_realserver.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }
}