package com.unnet.triangle.lvs.master.model;

public class Node {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.node_id
     *
     * @mbg.generated
     */
    private Long node_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.group_id
     *
     * @mbg.generated
     */
    private Long group_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.info
     *
     * @mbg.generated
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.node_id
     *
     * @return the value of node.node_id
     *
     * @mbg.generated
     */
    public Long getNode_id() {
        return node_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.node_id
     *
     * @param node_id the value for node.node_id
     *
     * @mbg.generated
     */
    public void setNode_id(Long node_id) {
        this.node_id = node_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.group_id
     *
     * @return the value of node.group_id
     *
     * @mbg.generated
     */
    public Long getGroup_id() {
        return group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.group_id
     *
     * @param group_id the value for node.group_id
     *
     * @mbg.generated
     */
    public void setGroup_id(Long group_id) {
        this.group_id = group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.host
     *
     * @return the value of node.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.host
     *
     * @param host the value for node.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.name
     *
     * @return the value of node.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.name
     *
     * @param name the value for node.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.state
     *
     * @return the value of node.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.state
     *
     * @param state the value for node.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.info
     *
     * @return the value of node.info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.info
     *
     * @param info the value for node.info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info;
    }
}