package com.unnet.triangle.lvs.master.model;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbg.generated
     */
    private Long task_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.node_id
     *
     * @mbg.generated
     */
    private Long node_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_type
     *
     * @mbg.generated
     */
    private String task_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.update_time
     *
     * @mbg.generated
     */
    private Date update_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.msg
     *
     * @mbg.generated
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbg.generated
     */
    public Long getTask_id() {
        return task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param task_id the value for task.task_id
     *
     * @mbg.generated
     */
    public void setTask_id(Long task_id) {
        this.task_id = task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.node_id
     *
     * @return the value of task.node_id
     *
     * @mbg.generated
     */
    public Long getNode_id() {
        return node_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.node_id
     *
     * @param node_id the value for task.node_id
     *
     * @mbg.generated
     */
    public void setNode_id(Long node_id) {
        this.node_id = node_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_type
     *
     * @return the value of task.task_type
     *
     * @mbg.generated
     */
    public String getTask_type() {
        return task_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_type
     *
     * @param task_type the value for task.task_type
     *
     * @mbg.generated
     */
    public void setTask_type(String task_type) {
        this.task_type = task_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.count
     *
     * @return the value of task.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.count
     *
     * @param count the value for task.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_time
     *
     * @return the value of task.create_time
     *
     * @mbg.generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_time
     *
     * @param create_time the value for task.create_time
     *
     * @mbg.generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.update_time
     *
     * @return the value of task.update_time
     *
     * @mbg.generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.update_time
     *
     * @param update_time the value for task.update_time
     *
     * @mbg.generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.data
     *
     * @return the value of task.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.data
     *
     * @param data the value for task.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.msg
     *
     * @return the value of task.msg
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.msg
     *
     * @param msg the value for task.msg
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }
}